AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Deploys two Amazon EC2 instances using EBS encryption via AWS KMS keys.
  One key is for development. One key is production.
  Last Edit - 2022.02.07 @ 1237 CT
Resources:
  Ec2DefaultEncryption:
    Type: "Custom::Ec2DefaultEncryption"
    Properties:
      KmsKeyId:
        Ref: "KmsKeyEc2DefaultEncryption"
      ServiceToken:
        Fn::GetAtt:
          - "Ec2DefaultEncryptionLambda"
          - "Arn"
  KmsKeyEc2DefaultEncryption:
    Type: "AWS::KMS::Key"
    Properties:
      EnableKeyRotation: true
      Description: "KMS Key for EBS default encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: "AWS::AccountId"
                    - ":root"
            Action: "kms:*"
            Resource: "*"
  KmsKeyAliasEc2DefaultEncryption:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: "alias/production"
      TargetKeyId:
        Ref: "KmsKeyEc2DefaultEncryption"
  KmsKeyEc2DefaultEncryption:
    Type: "AWS::KMS::Key"
    Properties:
      EnableKeyRotation: true
      Description: "KMS Key for EBS default encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: "AWS::AccountId"
                    - ":root"
            Action: "kms:*"
            Resource: "*"
  KmsKeyAliasEc2DefaultEncryption:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: "alias/production"
      TargetKeyId:
        Ref: "KmsKeyEc2DefaultEncryption"
  Ec2DefaultEncryptionLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
      Policies:
        - PolicyName: "kmsReadInline"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:DescribeKey"
                Resource: "*"
  Ec2DefaultEncryptionLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Fn::Sub:
            - "asecure-cloud-cf-aux-${Region}"
            - Region:
                Ref: "AWS::Region"
        S3Key: "ec2-enable-default-encryption-lambda.zip"
      Handler: "lambda_function.lambda_handler"w
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - "Ec2DefaultEncryptionLambdaRole"
          - "Arn"
      Runtime: "python3.9"
      Timeout: 120
Parameters: {}
Metadata: {}
Conditions: {}
